#!/usr/bin/env node

/**
 * Build script for the lens using esbuild
 * 
 * This script compiles TypeScript to JavaScript, bundles dependencies,
 * and optimizes the output for browser environments.
 * 
 * Features:
 * - TypeScript compilation
 * - Dependency bundling
 * - Minification
 * - Browser compatibility
 * - Source maps
 */

import * as esbuild from 'esbuild';
import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Configuration
const IS_PRODUCTION = process.env.NODE_ENV === 'production';
const IS_WATCH = process.argv.includes('--watch');

// Find all lens files in src directory
function findLensFiles() {
  const srcDir = path.join(__dirname, '../src');
  const files = fs.readdirSync(srcDir);
  
  return files
    .filter(file => file.endsWith('.ts') && !file.endsWith('.test.ts') && !file.endsWith('.d.ts'))
    .map(file => ({
      input: path.join(srcDir, file),
      output: path.join(__dirname, '../dist', file.replace('.ts', '.js')),
      name: file.replace('.ts', '')
    }));
}

async function build() {
  const lensFiles = findLensFiles();
  
  if (lensFiles.length === 0) {
    console.error('❌ No lens TypeScript files found in src/');
    process.exit(1);
  }

  console.log('🔨 Building lens files...');
  console.log(`   Mode: ${IS_PRODUCTION ? 'production' : 'development'}`);
  console.log(`   Watch: ${IS_WATCH ? 'enabled' : 'disabled'}`);
  
  for (const lens of lensFiles) {
    console.log(`\n📦 Building ${lens.name}...`);
    
    try {
      const buildOptions = {
        entryPoints: [lens.input],
        bundle: true,
        outfile: lens.output,
        format: 'iife',
        platform: 'browser',
        target: ['es2020'],
        minify: IS_PRODUCTION,
        sourcemap: !IS_PRODUCTION,
        treeShaking: true,
        legalComments: 'none',
        globalName: '__LENS_MODULE__',
        footer: {
          js: '\n// Convert module export to lens return format\nreturn __LENS_MODULE__.default;',
        },
        banner: {
          js: '// Gravitate Health Lens - Compiled with esbuild\n// Do not edit this file directly - edit the TypeScript source\n',
        },
        logLevel: 'info',
        loader: {
          '.ts': 'ts',
        },
        // Allow browser globals that will be provided at runtime
        define: {
          'process.env.NODE_ENV': `"${IS_PRODUCTION ? 'production' : 'development'}"`,
        },
      };

      if (IS_WATCH) {
        const ctx = await esbuild.context(buildOptions);
        await ctx.watch();
        console.log(`👀 Watching for changes...`);
      } else {
        await esbuild.build(buildOptions);
        
        // Get file size
        const stats = fs.statSync(lens.output);
        const fileSizeKB = (stats.size / 1024).toFixed(2);
        
        console.log(`✅ Successfully built ${lens.name}`);
        console.log(`   Output: ${lens.output}`);
        console.log(`   Size: ${fileSizeKB} KB`);
      }
    } catch (error) {
      console.error(`❌ Build failed for ${lens.name}:`, error);
      process.exit(1);
    }
  }
  
  if (!IS_WATCH) {
    console.log('\n✨ Build complete!');
    console.log('\n💡 Next steps:');
    console.log('   1. Test the lens: npm test');
    console.log('   2. Bundle into FHIR: npm run bundle');
  }
}

build().catch((error) => {
  console.error('❌ Build script error:', error);
  process.exit(1);
});
